name: Azure DevOps CI
 
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Trigger Azure DevOps Pipeline
      uses: azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/student10672/ML_LAB'
        azure-pipeline-name: 'ML_LAB'
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_ML_PAT}}'
